<?php
require_once ROOT_PATH . '/.env';

defined('AVIATIONSTACK_API_KEY')  || define('AVIATIONSTACK_API_KEY', $_ENV['AVIATIONSTACK_API_KEY']);
defined('AVIATIONSTACK_BASE_URL') || define('AVIATIONSTACK_BASE_URL', $_ENV['AVIATIONSTACK_BASE_URL']);

defined('RAPIDAPI_BOOKING_KEY')  || define('RAPIDAPI_BOOKING_KEY', $_ENV['RAPIDAPI_BOOKING_KEY']);
defined('RAPIDAPI_BOOKING_HOST') || define('RAPIDAPI_BOOKING_HOST', $_ENV['RAPIDAPI_BOOKING_HOST']);
